# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'XANavBarTransitionDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'XANavBarTransition', :path => '..'

  target 'XANavBarTransitionDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'XANavBarTransitionDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
